<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>


    <PackageId>MyBank.Shared.Core</PackageId>
    <Version>1.0.1</Version>
    <Authors>YourName</Authors>
    <Company>MyBank Inc.</Company>
    <Description>Shared core library for MyBank microservices.</Description>
    <RepositoryUrl>https://github.com/mhelmy12/BankSystem.Shared</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Carter" Version="8.2.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.0" />
    <PackageReference Include="MediatR" Version="12.5.0" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
  </ItemGroup>

</Project>
