<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Account_Service</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.15.0" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.83.0" />
    <PackageReference Include="IdGen" Version="3.0.7" />
    <PackageReference Include="IdGen.DependencyInjection" Version="3.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.18" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.18">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.18" />
    <PackageReference Include="MyBank.GrpcContracts.Core" Version="1.0.1" />
    <PackageReference Include="MyBank.Shared.Core" Version="1.0.3" />
    <PackageReference Include="StackExchange.Redis" Version="3.1.13" />
  </ItemGroup>

</Project>
